config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios
  devise_scope :usuario do
    authenticated :usuario do
      root 'anuncios#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :perfils
  resources :ocorrencia
  resources :anuncios
  resources :lancamentos_contabeis

  get 'lancamentos_contabeis/periodo/:periodo' => 'lancamentos_contabeis#no_periodo'

end

app/controllers/ocorrencia_controller.rb
class OcorrenciaController < ApplicationController
  before_action :set_ocorrencium, only: [:show, :edit, :update, :destroy]

  # GET /ocorrencia
  # GET /ocorrencia.json
  def index
    @ocorrencia = Ocorrencium.all
  end

  # GET /ocorrencia/1
  # GET /ocorrencia/1.json
  def show
  end

  # GET /ocorrencia/new
  def new
    @ocorrencium = Ocorrencium.new
  end

  # GET /ocorrencia/1/edit
  def edit
  end

  # POST /ocorrencia
  # POST /ocorrencia.json
  def create
    @ocorrencium = Ocorrencium.new(ocorrencium_params)

    respond_to do |format|
      if @ocorrencium.save
        format.html { redirect_to @ocorrencium, notice: 'Ocorrencium was successfully created.' }
        format.json { render :show, status: :created, location: @ocorrencium }
      else
        format.html { render :new }
        format.json { render json: @ocorrencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ocorrencia/1
  # PATCH/PUT /ocorrencia/1.json
  def update
    respond_to do |format|
      if @ocorrencium.update(ocorrencium_params)
        format.html { redirect_to @ocorrencium, notice: 'Ocorrencium was successfully updated.' }
        format.json { render :show, status: :ok, location: @ocorrencium }
      else
        format.html { render :edit }
        format.json { render json: @ocorrencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ocorrencia/1
  # DELETE /ocorrencia/1.json
  def destroy
    @ocorrencium.destroy
    respond_to do |format|
      format.html { redirect_to ocorrencia_url, notice: 'Ocorrencium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ocorrencium
      @ocorrencium = Ocorrencium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ocorrencium_params
      params.require(:ocorrencium).permit(:titulo, :data, :local, :descricao, :arquivo, :envolvidos)
    end
end

app/helpers/ocorrencia_helper.rb
module OcorrenciaHelper
end

app/views/ocorrencia/_form.html.erb
<%= form_for(@ocorrencium) do |f| %>
  <% if @ocorrencium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ocorrencium.errors.count, "error") %> prohibited this ocorrencium from being saved:</h2>

      <ul>
      <% @ocorrencium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :local %><br>
    <%= f.text_field :local %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :arquivo %><br>
    <%= f.file_field :arquivo %>
  </div>
  <div class="field">
    <%= f.label :envolvidos %><br>
    <%= f.text_field :envolvidos %>
  </div>
  <div class="actions">
    <%= f.submit 'Criar' %>
  </div>
<% end %>

app/views/ocorrencia/edit.html.erb
<h1>Editing Ocorrencium</h1>

<%= render 'form' %>

<%= link_to 'Show', @ocorrencium %> |
<%= link_to 'Back', ocorrencia_path %>

app/views/ocorrencia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ocorrencias</h1>

<table>
  
  <tbody>
    <% @ocorrencia.each do |ocorrencium| %>
      <tr>
        <td><%= ocorrencium.titulo %></td>
        <td><%= ocorrencium.data %></td>
        <td><%= ocorrencium.local %></td>
        <td><%= ocorrencium.descricao %></td>
        <td><%= ocorrencium.arquivo %></td>
        <td><%= ocorrencium.envolvidos %></td>
        <td><%= link_to 'Show', ocorrencium %><br />
        	<%= link_to 'Edit', edit_ocorrencium_path(ocorrencium) %><br />
        	<%= link_to 'Destroy', ocorrencium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Ocorrencia', new_ocorrencium_path %>

app/views/ocorrencia/new.html.erb
<h1>Nova Ocorrencia</h1>

<%= render 'form' %>

<%= link_to 'voltar', ocorrencia_path %>

app/views/ocorrencia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @ocorrencium.titulo %>
</p>

<p>
  <strong>Data:</strong>
  <%= @ocorrencium.data %>
</p>

<p>
  <strong>Local:</strong>
  <%= @ocorrencium.local %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @ocorrencium.descricao %>
</p>

<p>
  <strong>Arquivo:</strong>
  <%= @ocorrencium.arquivo %>
</p>

<p>
  <strong>Envolvidos:</strong>
  <%= @ocorrencium.envolvidos %>
</p>

<%= link_to 'Edit', edit_ocorrencium_path(@ocorrencium) %> |
<%= link_to 'Back', ocorrencia_path %>