config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios
  devise_scope :usuario do
    authenticated :usuario do
      root 'anuncios#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :perfils
  resources :ocorrencia
  resources :anuncios
  resources :lancamentos_contabeis

  get 'lancamentos_contabeis/periodo/:periodo' => 'lancamentos_contabeis#no_periodo'

end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
  belongs_to :usuario
  validates :usuario, presence: true
  /*add_foreign_key :usuario, dependent: :delete

def selecionarPerfil  
    current__usuario = perfil.find_by(perfil_id: usuario_id)
end*/
  
end

app/controllers/perfils_controller.rb
class PerfilsController < ApplicationController
  before_action :set_perfil, only: [:show, :edit, :update, :destroy]

  # GET /perfils
  # GET /perfils.json
  def index
    @perfils = Perfil.all
  end

  # GET /perfils/1
  # GET /perfils/1.json
  def show
  end

  # GET /perfils/new
  def new
    @perfil = Perfil.new
  end

  # GET /perfils/1/edit
  def edit
  end

  # POST /perfils
  # POST /perfils.json
  def create
    @perfil = Perfil.new(perfil_params)

    respond_to do |format|
      if @perfil.save
        format.html { redirect_to @perfil, notice: 'Perfil was successfully created.' }
        format.json { render :show, status: :created, location: @perfil }
      else
        format.html { render :new }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perfils/1
  # PATCH/PUT /perfils/1.json
  def update
    respond_to do |format|
      if @perfil.update(perfil_params)
        format.html { redirect_to @perfil, notice: 'Perfil was successfully updated.' }
        format.json { render :show, status: :ok, location: @perfil }
      else
        format.html { render :edit }
        format.json { render json: @perfil.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perfils/1
  # DELETE /perfils/1.json
  def destroy
    @perfil.destroy
    respond_to do |format|
      format.html { redirect_to perfils_url, notice: 'Perfil was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perfil
      @perfil = Perfil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perfil_params
      params.require(:perfil).permit(:usuario, :foto, :telefone, :dataNasc)
    end
end

app/helpers/perfils_helper.rb
module PerfilsHelper
end

app/views/perfils/_form.html.erb
<%= form_for(@perfil) do |f| %>
  <% if @perfil.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@perfil.errors.count, "error") %> prohibited this perfil from being saved:</h2>

      <ul>
      <% @perfil.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario %><br>
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :foto %><br>
    <%= f.file_field :foto %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :dataNasc, "Data de Nascimento" %><br>
    <%= f.date_select :dataNasc %>
  </div>
  <div class="actions">
    <%= f.submit 'Editar' %>
  </div>
<% end %>

app/views/perfils/edit.html.erb
<h1>Editing Perfil</h1>

<%= render 'form' %>

<%= link_to 'Show', @perfil %> |
<%= link_to 'Back', perfils_path %>

app/views/perfils/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Perfils</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Foto</th>
      <th>Telefone</th>
      <th>Datanasc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @perfils.each do |perfil| %>
      <tr>
        <td><%= perfil.usuario %></td>
        <td><%= perfil.foto %></td>
        <td><%= perfil.telefone %></td>
        <td><%= perfil.dataNasc %></td>
        <td><%= link_to 'Show', perfil %></td>
        <td><%= link_to 'Edit', edit_perfil_path(perfil) %></td>
        <td><%= link_to 'Destroy', perfil, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Perfil', new_perfil_path %>

app/views/perfils/new.html.erb
<h1>Perfil</h1>

<%= render 'form' %>

<%= link_to 'Back', perfils_path %>

app/views/perfils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @perfil.usuario %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @perfil.foto %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @perfil.telefone %>
</p>

<p>
  <strong>Datanasc:</strong>
  <%= @perfil.dataNasc %>
</p>

<%= link_to 'Edit', edit_perfil_path(@perfil) %> |
<%= link_to 'Back', perfils_path %>