config/routes.rb
Rails.application.routes.draw do

  devise_for :usuarios
  devise_scope :usuario do
    authenticated :usuario do
      root 'anuncios#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :perfils
  resources :ocorrencia
  resources :anuncios
  resources :lancamentos_contabeis

  get 'lancamentos_contabeis/periodo/:periodo' => 'lancamentos_contabeis#no_periodo'

end

app/models/anuncio.rb
class Anuncio < ActiveRecord::Base
end

app/controllers/anuncios_controller.rb
class AnunciosController < ApplicationController
  before_action :set_anuncio, only: [:show, :edit, :update, :destroy]

  # GET /anuncios
  # GET /anuncios.json
  def index
    @anuncios = Anuncio.all
  end

  # GET /anuncios/1
  # GET /anuncios/1.json
  def show
  end

  # GET /anuncios/new
  def new
    @anuncio = Anuncio.new
  end

  # GET /anuncios/1/edit
  def edit
  end

  # POST /anuncios
  # POST /anuncios.json
  def create
    @anuncio = Anuncio.new(anuncio_params)

    respond_to do |format|
      if @anuncio.save
        format.html { redirect_to @anuncio, notice: 'Anuncio was successfully created.' }
        format.json { render :show, status: :created, location: @anuncio }
      else
        format.html { render :new }
        format.json { render json: @anuncio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anuncios/1
  # PATCH/PUT /anuncios/1.json
  def update
    respond_to do |format|
      if @anuncio.update(anuncio_params)
        format.html { redirect_to @anuncio, notice: 'Anuncio was successfully updated.' }
        format.json { render :show, status: :ok, location: @anuncio }
      else
        format.html { render :edit }
        format.json { render json: @anuncio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anuncios/1
  # DELETE /anuncios/1.json
  def destroy
    @anuncio.destroy
    respond_to do |format|
      format.html { redirect_to anuncios_url, notice: 'Anuncio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def upload
  path = File.join(Rails.root, 
  "assets/images", 
  params[:usuario][:anexo].original_filename)

# escreve o arquivo no local designado
File.open(path, "") do |f| 
  f.write(params[:usuario][:anexo].read)
end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anuncio
      @anuncio = Anuncio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anuncio_params
      params.require(:anuncio).permit(:tipo, :titulo, :descricao, :anexo)
    end
end

app/views/anuncios/_form.html.erb
<%= form_for(@anuncio, :html => { :multipart => true }) do |f| %>
  <% if @anuncio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anuncio.errors.count, "error") %> prohibited this anuncio from being saved:</h2>

      <ul>
      <% @anuncio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.number_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :anexo %><br>
    <%= f.file_field :anexo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/anuncios/edit.html.erb
<h1>Editing Anuncio</h1>

<%= render 'form' %>

<%= link_to 'Show', @anuncio %> |
<%= link_to 'Back', anuncios_path %>

app/views/anuncios/index.html.erb
<p id="notice">
	<%= notice %>
</p>

<h1>Classificados</h1>
<div class="row">
	<% @anuncios.each do |anuncio| %>
	<div class="col-sm-3 col-md-2 sidebar">
		<div class="<%= cycle('list_line_odd', 'list_line_even') %>">
			<p class="foto" ><%= image_tag(anuncio.anexo, class: 'foto') %></p>
			<p>
				<%= anuncio.tipo %>) <%= anuncio.titulo %>
			</p>
			<p>
				<%= anuncio.descricao %>
			</p>
			<p>
				<%= link_to '>>', anuncio %>
				<%= link_to '', edit_anuncio_path(anuncio), :class=>"glyphicon glyphicon-pencil" %>
				<%= link_to '', anuncio, method: :delete, :class=>"glyphicon glyphicon-remove", data: { confirm: 'Are you sure?'}%>
			</p>
		</div>
	</div>
	<% end %>
</div>

<br>

<%= link_to 'Anunciar', new_anuncio_path %>

app/views/anuncios/new.html.erb
<h1>Novo Anuncio</h1>

<%= render 'form' %>

<%= link_to 'Voltar', anuncios_path %>

app/views/anuncios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @anuncio.tipo %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @anuncio.titulo %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @anuncio.descricao %>
</p>

<p>
  <strong>Anexo:</strong>
  <%= @anuncio.anexo %>
</p>

<%= link_to 'Edit', edit_anuncio_path(@anuncio) %> |
<%= link_to 'Back', anuncios_path %>